#!/bin/bash

wget https://registry.npmjs.org/accepts/-/accepts-1.3.3.tgz
wget https://registry.npmjs.org/align-text/-/align-text-0.1.4.tgz
wget https://registry.npmjs.org/amdefine/-/amdefine-1.0.1.tgz
wget https://registry.npmjs.org/array-flatten/-/array-flatten-1.1.1.tgz
wget https://registry.npmjs.org/asap/-/asap-2.0.5.tgz
wget https://registry.npmjs.org/async/-/async-1.5.2.tgz
wget https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz
wget https://registry.npmjs.org/bignumber.js/-/bignumber.js-4.0.2.tgz
wget https://registry.npmjs.org/body-parser/-/body-parser-1.16.1.tgz
wget https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.8.tgz
wget https://registry.npmjs.org/bytes/-/bytes-2.4.0.tgz
wget https://registry.npmjs.org/camelcase/-/camelcase-1.2.1.tgz
wget https://registry.npmjs.org/center-align/-/center-align-0.1.3.tgz
wget https://registry.npmjs.org/cliui/-/cliui-2.1.0.tgz,
wget https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz
wget https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz
wget https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.2.tgz
wget https://registry.npmjs.org/content-type/-/content-type-1.0.2.tgz
wget https://registry.npmjs.org/cookie/-/cookie-0.3.1.tgz
wget https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.6.tgz
wget https://registry.npmjs.org/crc/-/crc-3.4.4.tgz
wget https://registry.npmjs.org/crypto-js/-/crypto-js-3.1.8.tgz
wget https://registry.npmjs.org/debug/-/debug-2.6.1.tgz
wget https://registry.npmjs.org/decamelize/-/decamelize-1.2.0.tgz
wget https://registry.npmjs.org/define-properties/-/define-properties-1.1.2.tgz
wget https://registry.npmjs.org/depd/-/depd-1.1.0.tgz
wget https://registry.npmjs.org/destroy/-/destroy-1.0.4.tgz
wget https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz
wget https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.1.tgz
wget https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz
wget https://registry.npmjs.org/etag/-/etag-1.8.0.tgz
wget https://registry.npmjs.org/express/-/express-4.15.3.tgz,
wget https://registry.npmjs.org/debug/-/debug-2.6.7.tgz
wget https://registry.npmjs.org/ms/-/ms-2.0.0.tgz
wget https://registry.npmjs.org/qs/-/qs-6.4.0.tgz
wget https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.0.3.tgz
wget https://registry.npmjs.org/express-handlebars/-/express-handlebars-3.0.0.tgz
wget https://registry.npmjs.org/express-session/-/express-session-1.15.3.tgz,
wget https://registry.npmjs.org/debug/-/debug-2.6.7.tgz
wget https://registry.npmjs.org/ms/-/ms-2.0.0.tgz
wget https://registry.npmjs.org/finalhandler/-/finalhandler-1.0.3.tgz,
wget https://registry.npmjs.org/debug/-/debug-2.6.7.tgz
wget https://registry.npmjs.org/ms/-/ms-2.0.0.tgz
wget https://registry.npmjs.org/foreach/-/foreach-2.0.5.tgz
wget https://registry.npmjs.org/forwarded/-/forwarded-0.1.0.tgz
wget https://registry.npmjs.org/fresh/-/fresh-0.5.0.tgz
wget https://registry.npmjs.org/function-bind/-/function-bind-1.1.0.tgz
wget https://registry.npmjs.org/glob/-/glob-6.0.4.tgz
wget https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz
wget https://registry.npmjs.org/handlebars/-/handlebars-4.0.10.tgz
wget https://registry.npmjs.org/http-errors/-/http-errors-1.5.1.tgz
wget https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.15.tgz
wget https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz
wget https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz
wget https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.3.0.tgz
wget https://registry.npmjs.org/is-buffer/-/is-buffer-1.1.5.tgz
wget https://registry.npmjs.org/kind-of/-/kind-of-3.2.2.tgz
wget https://registry.npmjs.org/lazy-cache/-/lazy-cache-1.0.4.tgz
wget https://registry.npmjs.org/longest/-/longest-1.0.1.tgz
wget https://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz
wget https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-1.0.1.tgz
wget https://registry.npmjs.org/methods/-/methods-1.1.2.tgz
wget https://registry.npmjs.org/mime/-/mime-1.3.4.tgz
wget https://registry.npmjs.org/mime-db/-/mime-db-1.27.0.tgz
wget https://registry.npmjs.org/mime-types/-/mime-types-2.1.15.tgz
wget https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz
wget https://registry.npmjs.org/minimist/-/minimist-0.0.10.tgz
wget https://registry.npmjs.org/moment/-/moment-2.17.1.tgz
wget https://registry.npmjs.org/ms/-/ms-0.7.2.tgz
wget https://registry.npmjs.org/negotiator/-/negotiator-0.6.1.tgz
wget https://registry.npmjs.org/object-keys/-/object-keys-1.0.11.tgz
wget https://registry.npmjs.org/object.assign/-/object.assign-4.0.4.tgz
wget https://registry.npmjs.org/on-headers/-/on-headers-1.0.1.tgz
wget https://registry.npmjs.org/once/-/once-1.4.0.tgz
wget https://registry.npmjs.org/optimist/-/optimist-0.6.1.tgz
wget https://registry.npmjs.org/parseurl/-/parseurl-1.3.1.tgz
wget https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz
wget https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-0.1.7.tgz
wget https://registry.npmjs.org/promise/-/promise-7.1.1.tgz
wget https://registry.npmjs.org/proxy-addr/-/proxy-addr-1.1.4.tgz
wget https://registry.npmjs.org/qs/-/qs-6.2.1.tgz
wget https://registry.npmjs.org/random-bytes/-/random-bytes-1.0.0.tgz
wget https://registry.npmjs.org/range-parser/-/range-parser-1.2.0.tgz
wget https://registry.npmjs.org/raw-body/-/raw-body-2.2.0.tgz
wget https://registry.npmjs.org/repeat-string/-/repeat-string-1.6.1.tgz
wget https://registry.npmjs.org/right-align/-/right-align-0.1.3.tgz
wget https://registry.npmjs.org/send/-/send-0.15.3.tgz,
wget https://registry.npmjs.org/debug/-/debug-2.6.7.tgz
wget https://registry.npmjs.org/http-errors/-/http-errors-1.6.1.tgz
wget https://registry.npmjs.org/ms/-/ms-2.0.0.tgz
wget https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.0.3.tgz
wget https://registry.npmjs.org/serve-static/-/serve-static-1.12.3.tgz
wget https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.0.2.tgz
wget https://registry.npmjs.org/source-map/-/source-map-0.4.4.tgz
wget https://registry.npmjs.org/statuses/-/statuses-1.3.1.tgz
wget https://registry.npmjs.org/type-is/-/type-is-1.6.15.tgz
wget https://registry.npmjs.org/uglify-js/-/uglify-js-2.8.29.tgz,
wget https://registry.npmjs.org/source-map/-/source-map-0.5.6.tgz
wget https://registry.npmjs.org/uglify-to-browserify/-/uglify-to-browserify-1.0.2.tgz
wget https://registry.npmjs.org/uid-safe/-/uid-safe-2.1.4.tgz
wget https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz
wget https://registry.npmjs.org/utf8/-/utf8-2.1.2.tgz
wget https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.0.tgz
wget https://registry.npmjs.org/vary/-/vary-1.1.1.tgz
wget https://registry.npmjs.org/web3/-/web3-0.19.1.tgz
wget https://registry.npmjs.org/window-size/-/window-size-0.1.0.tgz
wget https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz
wget https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz
wget https://registry.npmjs.org/xhr2/-/xhr2-0.1.4.tgz
wget https://registry.npmjs.org/xmlhttprequest/-/xmlhttprequest-1.8.0.tgz
wget https://registry.npmjs.org/yargs/-/yargs-3.10.0.tgz
